import {
  CanonicalApiModel,
  ApiEndpoint,
  ApiSchema,
  ApiSchemaProperty,
  ApiParameter,
} from "../parser/canonical-model";
import { GeneratedSdk, SdkFile, SdkOptions } from "./sdk.types";

export class TypeScriptSdkGenerator {
  /**
   * Generates a type-safe TypeScript SDK from a CanonicalApiModel
   */
  public generate(model: CanonicalApiModel, options: SdkOptions = {}): GeneratedSdk {
    const rawName =
      options.clientName ||
      model.metadata?.title?.replace(/[^a-zA-Z0-9]/g, "") ||
      "AtlasApi";
    const clientName = this.toPascalCase(rawName);
    const version = model.metadata?.version || "1.0.0";
    const baseUrl = options.baseUrl || "https://api.example.com";

    const typesFile = this.generateTypesFile(model);
    const clientFile = this.generateClientFile(model, clientName, baseUrl);
    const indexFile = this.generateIndexFile(clientName);

    return {
      clientName: `${clientName}Client`,
      version,
      files: [typesFile, clientFile, indexFile],
    };
  }

  private generateTypesFile(model: CanonicalApiModel): SdkFile {
    const lines: string[] = [
      "/**",
      ` * Auto-generated TypeScript types for ${model.metadata?.title || "API"}`,
      ` * API Version: ${model.metadata?.version || "1.0.0"}`,
      ` * Generated by ATLAS — API Engineering Workbench`,
      " */",
      "",
    ];

    // 1. Generate interfaces for all schemas
    if (model.schemas && model.schemas.length > 0) {
      lines.push("// =============================================================================");
      lines.push("// Schemas");
      lines.push("// =============================================================================");
      lines.push("");

      for (const schema of model.schemas) {
        if (schema.description) {
          lines.push("/**");
          lines.push(` * ${schema.description.replace(/\n/g, "\n * ")}`);
          lines.push(" */");
        }
        lines.push(`export interface ${this.toPascalCase(schema.name)} {`);

        if (schema.properties && schema.properties.length > 0) {
          for (const prop of schema.properties) {
            const isRequired = schema.required?.includes(prop.name) || prop.required;
            const optionalFlag = isRequired ? "" : "?";
            const tsType = this.mapPropertyType(prop);

            if (prop.description) {
              lines.push(`  /** ${prop.description} */`);
            }
            lines.push(`  ${this.sanitizePropertyName(prop.name)}${optionalFlag}: ${tsType};`);
          }
        } else {
          lines.push("  [key: string]: unknown;");
        }

        lines.push("}");
        lines.push("");
      }
    }

    // 2. Generate endpoint parameter & payload interfaces
    if (model.endpoints && model.endpoints.length > 0) {
      lines.push("// =============================================================================");
      lines.push("// Endpoint Parameter & Request Interfaces");
      lines.push("// =============================================================================");
      lines.push("");

      for (const ep of model.endpoints) {
        const opName = this.getOperationName(ep);
        const queryParams = ep.parameters?.filter((p) => p.location === "query") || [];
        const pathParams = ep.parameters?.filter((p) => p.location === "path") || [];
        const headerParams = ep.parameters?.filter((p) => p.location === "header") || [];

        if (queryParams.length > 0) {
          lines.push(`export interface ${this.toPascalCase(opName)}QueryParams {`);
          for (const p of queryParams) {
            const opt = p.required ? "" : "?";
            const tsType = this.mapPrimitiveType(p.schemaType);
            if (p.description) lines.push(`  /** ${p.description} */`);
            lines.push(`  ${this.sanitizePropertyName(p.name)}${opt}: ${tsType};`);
          }
          lines.push("}");
          lines.push("");
        }

        if (pathParams.length > 0) {
          lines.push(`export interface ${this.toPascalCase(opName)}PathParams {`);
          for (const p of pathParams) {
            const opt = p.required ? "" : "?";
            const tsType = this.mapPrimitiveType(p.schemaType);
            if (p.description) lines.push(`  /** ${p.description} */`);
            lines.push(`  ${this.sanitizePropertyName(p.name)}${opt}: ${tsType};`);
          }
          lines.push("}");
          lines.push("");
        }

        if (headerParams.length > 0) {
          lines.push(`export interface ${this.toPascalCase(opName)}HeaderParams {`);
          for (const p of headerParams) {
            const opt = p.required ? "" : "?";
            const tsType = this.mapPrimitiveType(p.schemaType);
            if (p.description) lines.push(`  /** ${p.description} */`);
            lines.push(`  ${this.sanitizePropertyName(p.name)}${opt}: ${tsType};`);
          }
          lines.push("}");
          lines.push("");
        }
      }
    }

    return {
      filename: "types.ts",
      content: lines.join("\n"),
      language: "typescript",
    };
  }

  private generateClientFile(
    model: CanonicalApiModel,
    clientName: string,
    baseUrl: string
  ): SdkFile {
    const fullClientName = `${clientName}Client`;
    const lines: string[] = [
      "/**",
      ` * Auto-generated Client for ${model.metadata?.title || "API"}`,
      ` * Generated by ATLAS — API Engineering Workbench`,
      " */",
      "",
      'import * as Types from "./types";',
      "",
      "export interface ClientConfig {",
      `  baseUrl?: string;`,
      "  token?: string; // Bearer token",
      "  apiKey?: string;",
      "  headers?: Record<string, string>;",
      "  fetch?: typeof fetch;",
      "}",
      "",
      "export class ApiClientError extends Error {",
      "  public status: number;",
      "  public statusText: string;",
      "  public data: unknown;",
      "",
      "  constructor(message: string, status: number, statusText: string, data?: unknown) {",
      "    super(message);",
      '    this.name = "ApiClientError";',
      "    this.status = status;",
      "    this.statusText = statusText;",
      "    this.data = data;",
      "  }",
      "}",
      "",
      `export class ${fullClientName} {`,
      "  private baseUrl: string;",
      "  private token?: string;",
      "  private apiKey?: string;",
      "  private customHeaders: Record<string, string>;",
      "  private customFetch: typeof fetch;",
      "",
      "  constructor(config: ClientConfig = {}) {",
      `    this.baseUrl = (config.baseUrl || "${baseUrl}").replace(/\\/+$/, "");`,
      "    this.token = config.token;",
      "    this.apiKey = config.apiKey;",
      "    this.customHeaders = config.headers || {};",
      "    this.customFetch = config.fetch || (typeof fetch !== 'undefined' ? fetch : (globalThis as any).fetch);",
      "  }",
      "",
      "  /**",
      "   * Internal request dispatcher",
      "   */",
      "  private async request<T>(",
      "    method: string,",
      "    path: string,",
      "    options: {",
      "      params?: Record<string, string | number | boolean | undefined>;",
      "      query?: Record<string, string | number | boolean | undefined>;",
      "      headers?: Record<string, string | undefined>;",
      "      body?: unknown;",
      "    } = {}",
      "  ): Promise<T> {",
      "    let resolvedPath = path;",
      "    if (options.params) {",
      "      for (const [k, v] of Object.entries(options.params)) {",
      "        if (v !== undefined) {",
      "          resolvedPath = resolvedPath.replace(`{${k}}`, encodeURIComponent(String(v)));",
      "        }",
      "      }",
      "    }",
      "",
      "    let url = `${this.baseUrl}${resolvedPath}`;",
      "    if (options.query) {",
      "      const searchParams = new URLSearchParams();",
      "      for (const [k, v] of Object.entries(options.query)) {",
      "        if (v !== undefined && v !== null) {",
      "          searchParams.append(k, String(v));",
      "        }",
      "      }",
      "      const queryString = searchParams.toString();",
      "      if (queryString) {",
      "        url += (url.includes('?') ? '&' : '?') + queryString;",
      "      }",
      "    }",
      "",
      "    const headers: Record<string, string> = {",
      "      ...this.customHeaders,",
      "    };",
      "",
      "    if (this.token) {",
      "      headers['Authorization'] = `Bearer ${this.token}`;",
      "    }",
      "    if (this.apiKey) {",
      "      headers['X-API-Key'] = this.apiKey;",
      "    }",
      "",
      "    if (options.headers) {",
      "      for (const [k, v] of Object.entries(options.headers)) {",
      "        if (v !== undefined) {",
      "          headers[k] = String(v);",
      "        }",
      "      }",
      "    }",
      "",
      "    let bodyPayload: string | undefined;",
      "    if (options.body !== undefined) {",
      "      headers['Content-Type'] = headers['Content-Type'] || 'application/json';",
      "      bodyPayload = JSON.stringify(options.body);",
      "    }",
      "",
      "    const response = await this.customFetch(url, {",
      "      method,",
      "      headers,",
      "      body: bodyPayload,",
      "    });",
      "",
      "    if (!response.ok) {",
      "      let errorBody: unknown;",
      "      try {",
      "        errorBody = await response.json();",
      "      } catch {",
      "        errorBody = await response.text();",
      "      }",
      "      throw new ApiClientError(",
      "        `API request failed with status ${response.status}: ${response.statusText}`,",
      "        response.status,",
      "        response.statusText,",
      "        errorBody",
      "      );",
      "    }",
      "",
      "    if (response.status === 204) {",
      "      return undefined as unknown as T;",
      "    }",
      "",
      "    const contentType = response.headers.get('content-type') || '';",
      "    if (contentType.includes('application/json')) {",
      "      return (await response.json()) as T;",
      "    }",
      "    return (await response.text()) as unknown as T;",
      "  }",
      "",
    ];

    // Generate methods for each endpoint
    if (model.endpoints) {
      for (const ep of model.endpoints) {
        this.generateEndpointMethod(ep, lines);
      }
    }

    lines.push("}");
    lines.push("");

    return {
      filename: "client.ts",
      content: lines.join("\n"),
      language: "typescript",
    };
  }

  private generateEndpointMethod(ep: ApiEndpoint, lines: string[]): void {
    const opName = this.getOperationName(ep);
    const queryParams = ep.parameters?.filter((p) => p.location === "query") || [];
    const pathParams = ep.parameters?.filter((p) => p.location === "path") || [];
    const headerParams = ep.parameters?.filter((p) => p.location === "header") || [];
    const hasBody = !!ep.requestBody;

    // Determine return type
    const returnType = this.determineReturnType(ep);

    // Build argument list
    const args: string[] = [];

    // Path parameters
    if (pathParams.length === 1) {
      const p = pathParams[0];
      const type = this.mapPrimitiveType(p.schemaType);
      args.push(`${this.toCamelCase(p.name)}: ${type}`);
    } else if (pathParams.length > 1) {
      args.push(`params: Types.${this.toPascalCase(opName)}PathParams`);
    }

    // Request body
    if (hasBody) {
      let bodyType = "unknown";
      if (ep.requestBody?.schemaRef) {
        const refName = this.extractRefName(ep.requestBody.schemaRef);
        bodyType = `Types.${this.toPascalCase(refName)}`;
      } else if (ep.requestBody?.schemaType) {
        bodyType = this.mapPrimitiveType(ep.requestBody.schemaType);
      }
      args.push(`body: ${bodyType}`);
    }

    // Query parameters
    if (queryParams.length > 0) {
      const allOptional = queryParams.every((q) => !q.required);
      args.push(`query${allOptional ? "?" : ""}: Types.${this.toPascalCase(opName)}QueryParams`);
    }

    // Header parameters
    if (headerParams.length > 0) {
      const allOptional = headerParams.every((h) => !h.required);
      args.push(`headers${allOptional ? "?" : ""}: Types.${this.toPascalCase(opName)}HeaderParams`);
    }

    // JSDoc
    lines.push("  /**");
    if (ep.summary) lines.push(`   * ${ep.summary}`);
    if (ep.description && ep.description !== ep.summary) {
      lines.push(`   * ${ep.description.replace(/\n/g, "\n   * ")}`);
    }
    lines.push(`   * ${ep.method.toUpperCase()} ${ep.path}`);
    lines.push("   */");

    lines.push(`  public async ${this.toCamelCase(opName)}(${args.join(", ")}): Promise<${returnType}> {`);

    // Prepare params mapping
    let paramsCode = "params: undefined";
    if (pathParams.length === 1) {
      paramsCode = `params: { '${pathParams[0].name}': ${this.toCamelCase(pathParams[0].name)} }`;
    } else if (pathParams.length > 1) {
      paramsCode = "params: params as any";
    }

    const queryCode = queryParams.length > 0 ? "query: query as any" : "query: undefined";
    const headersCode = headerParams.length > 0 ? "headers: headers as any" : "headers: undefined";
    const bodyCode = hasBody ? "body" : "body: undefined";

    lines.push(`    return this.request<${returnType}>('${ep.method.toUpperCase()}', '${ep.path}', {`);
    lines.push(`      ${paramsCode},`);
    lines.push(`      ${queryCode},`);
    lines.push(`      ${headersCode},`);
    lines.push(`      ${bodyCode},`);
    lines.push("    });");
    lines.push("  }");
    lines.push("");
  }

  private generateIndexFile(clientName: string): SdkFile {
    const fullClientName = `${clientName}Client`;
    const lines = [
      "/**",
      ` * ATLAS API Client SDK Entry Point`,
      " */",
      "",
      'export * from "./types";',
      'export * from "./client";',
      `export { ${fullClientName} as default } from "./client";`,
      "",
    ];

    return {
      filename: "index.ts",
      content: lines.join("\n"),
      language: "typescript",
    };
  }

  private determineReturnType(ep: ApiEndpoint): string {
    const successRes =
      ep.responses?.find((r) => r.statusCode.startsWith("2")) ||
      ep.responses?.find((r) => r.statusCode === "default");

    if (!successRes) return "unknown";
    if (successRes.statusCode === "204") return "void";

    if (successRes.schemaRef) {
      const refName = this.extractRefName(successRes.schemaRef);
      if (successRes.schemaType === "array") {
        return `Types.${this.toPascalCase(refName)}[]`;
      }
      return `Types.${this.toPascalCase(refName)}`;
    }

    if (successRes.schemaType === "array") {
      return "unknown[]";
    }

    if (successRes.schemaType) {
      return this.mapPrimitiveType(successRes.schemaType);
    }

    return "unknown";
  }

  private mapPropertyType(prop: ApiSchemaProperty): string {
    if (prop.reference) {
      const ref = this.extractRefName(prop.reference);
      const pascalRef = this.toPascalCase(ref);
      return prop.type === "array" ? `${pascalRef}[]` : pascalRef;
    }

    if (prop.type === "array") {
      if (prop.itemsType) {
        return `${this.mapPrimitiveType(prop.itemsType)}[]`;
      }
      return "unknown[]";
    }

    return this.mapPrimitiveType(prop.type);
  }

  private mapPrimitiveType(type?: string): string {
    switch (type) {
      case "integer":
      case "number":
        return "number";
      case "string":
        return "string";
      case "boolean":
        return "boolean";
      case "object":
        return "Record<string, unknown>";
      default:
        return "unknown";
    }
  }

  private getOperationName(ep: ApiEndpoint): string {
    if (ep.operationId && ep.operationId.trim()) {
      return ep.operationId.replace(/[^a-zA-Z0-9_]/g, "");
    }

    const cleanPath = ep.path
      .replace(/\{([^}]+)\}/g, "By-$1")
      .split(/[^a-zA-Z0-9]/)
      .filter(Boolean)
      .map((seg) => this.toPascalCase(seg))
      .join("");

    return `${ep.method.toLowerCase()}${cleanPath}`;
  }

  private extractRefName(ref: string): string {
    const parts = ref.split("/");
    return parts[parts.length - 1] || "Schema";
  }

  private toPascalCase(str: string): string {
    if (!str) return "Item";
    return str
      .replace(/[-_ ]+([a-zA-Z0-9])/g, (_, c) => c.toUpperCase())
      .replace(/^[a-z]/, (c) => c.toUpperCase())
      .replace(/[^a-zA-Z0-9]/g, "");
  }

  private toCamelCase(str: string): string {
    if (!str) return "item";
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }

  private sanitizePropertyName(name: string): string {
    if (/^[a-zA-Z_$][a-zA-Z0-9_$]*$/.test(name)) {
      return name;
    }
    return JSON.stringify(name);
  }
}

export const typeScriptSdkGenerator = new TypeScriptSdkGenerator();
